default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  compile: true

  # Cache manifest.json for performance
  cache_manifest: true

  # Extract and emit a css file
  extract_css: false

  # When set to true, webpacker will compile on-demand in the production environment
  # when a webpacker asset is requested that has not been compiled.
  compile: false

  # Verbose output of webpack compilation logs
  verbose: false

development:
  <<: *default
  compile: true

  # Webpack dev server config
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'

production:
  <<: *default
  compile: false
  extract_css: true
  cache_manifest: true
